#!/usr/bin/env bash

IFS='' read -r -d '' code <<"EOF"
# Store interactive Python shell history in ~/.cache/python_history
# instead of ~/.python_history.

import atexit
import os
import readline

histfile = os.path.join(os.getenv("XDG_CACHE_HOME", os.path.expanduser("~/.cache")), "python_history")
try:
    readline.read_history_file(histfile)
    # default history len is -1 (infinite), which may grow unruly
    readline.set_history_length(1000)
except FileNotFoundError:
    pass

atexit.register(readline.write_history_file, histfile)

import sys

sys.ps1 = "lbldb> "
sys.ps2 = "       "

from lbldb import *
EOF

python -i -c "${code}"
